import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { HelloWorld2GeneratedModule, HelloWorld2GeneratedSharedModule } from './generated/module';
import { HelloWorld2Validator, registerValidationChecks } from './hello-world-2-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type HelloWorld2AddedServices = {
    validation: {
        HelloWorld2Validator: HelloWorld2Validator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type HelloWorld2Services = LangiumServices & HelloWorld2AddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const HelloWorld2Module: Module<HelloWorld2Services, PartialLangiumServices & HelloWorld2AddedServices> = {
    validation: {
        HelloWorld2Validator: () => new HelloWorld2Validator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createHelloWorld2Services(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    HelloWorld2: HelloWorld2Services
} {
    const shared = inject(
        createDefaultSharedModule(context),
        HelloWorld2GeneratedSharedModule
    );
    const HelloWorld2 = inject(
        createDefaultModule({ shared }),
        HelloWorld2GeneratedModule,
        HelloWorld2Module
    );
    shared.ServiceRegistry.register(HelloWorld2);
    registerValidationChecks(HelloWorld2);
    return { shared, HelloWorld2 };
}
